services:
  # app:
  #   build: .
  #   image: watchtower
  #   container_name: watchtower
  #   restart: always
  #   network_mode: 'host'
  #   # ports:
  #   #   - '127.0.0.1:3000:3000'
  #   logging: # apply better controls to Docker overlay folder
  #     driver: 'json-file'
  #     options:
  #       max-file: '5'
  #       max-size: '10m'
  #   environment:
  #     - COUCHDB_USER=${COUCHDB_USER}
  #     - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
  #     - EXPORT_STAGING=/export
  #   volumes:
  #       - ${EXPORT_STAGING}:/export
  couchdb:
    image: couchdb
    restart: always
    ports:
      - '127.0.0.1:5984:5984'
      - '127.0.0.1:4369:4369'
      - '127.0.0.1:9100:9100'
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    volumes:
        - ./data:/opt/couchdb/data
    logging: # apply better controls to Docker overlay folder
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'
