version: '3.7'

services:
  app:
    build: .
    image: nexa-garden
    container_name: nexa-garden
    restart: always
    network_mode: 'host'
    # ports:
    #   - '127.0.0.1:3000:3000'
    logging: # apply better controls to Docker overlay folder
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'
    environment:
      - HELIA_DIR=/helia
      - UPLOAD_DIR=/uploads
      - MNEMONIC=${MNEMONIC}
    volumes:
        - ${HELIA_DIR}:/helia
        - ${UPLOAD_DIR}:/uploads
        # WARNING This is very dangerous, as it gives 100% control over the host machine's Docker instance.
        #         However, this is the "preferred" way to execute CLI on another container.
        #         (source: https://nathanleclaire.com/blog/2014/07/12/10-docker-tips-and-tricks-that-will-make-you-sing-a-whale-song-of-joy/)
        # - '/var/run/docker.sock:/var/run/docker.sock'
  couchdb:
    image: couchdb
    restart: always
    ports:
      - '127.0.0.1:5984:5984'
      - '127.0.0.1:4369:4369'
      - '127.0.0.1:9100:9100'
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    volumes:
        - ./data:/opt/couchdb/data
    logging: # apply better controls to Docker overlay folder
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'
