version: '3.7'

services:
  app:
    build: .
    image: nexa-garden
    container_name: nexa-garden
    restart: always
    ports:
      - '127.0.0.1:3000:3000'   # use with proxy server (eg. Nginx)
      # - '0.0.0.0:80:3000'     # use without proxy server
    logging: # apply better controls to Docker overlay folder
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'
    environment:
      - PROJECT_ID=${PROJECT_ID}
      - PROJECT_NAME=${PROJECT_NAME}
      - PROJECT_MNEMONIC=${PROJECT_MNEMONIC}
    volumes:
        - ${IPFS_STAGING}:/export
  couchdb:
    image: couchdb
    restart: always
    ports:
      - '127.0.0.1:5984:5984'
      - '127.0.0.1:4369:4369'
      - '127.0.0.1:9100:9100'
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    volumes:
        - ./data:/opt/couchdb/data
    logging: # apply better controls to Docker overlay folder
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'
